# INTEL CONFIDENTIAL
# Copyright (2019) Intel Corporation.

# The source code contained or described herein and all documents related to the source code ("Material")
# are owned by Intel Corporation or its suppliers or licensors. Title to the Material remains with
# Intel Corporation or its suppliers and licensors. The Material may contain trade secrets and proprietary
# and confidential information of Intel Corporation and its suppliers and licensors, and is protected by
# worldwide copyright and trade secret laws and treaty provisions. No part of the Material may be used,
# copied, reproduced, modified, published, uploaded, posted, transmitted, distributed, or disclosed in
# any way without Intel/'s prior express written permission.
# No license under any patent, copyright, trade secret or other intellectual property right is granted
# to or conferred upon you by disclosure or delivery of the Materials, either expressly, by implication,
# inducement, estoppel or otherwise. Any license under such intellectual property rights must be express
# and approved by Intel in writing.
# Unless otherwise agreed by Intel in writing, you may not remove or alter this notice or any other
# notice embedded in Materials by Intel or Intel's suppliers or licensors in any way. 

version: '3.4'

volumes:
  product-data: 

networks:
  main-net:

services:  

  postgres-inventory:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    networks:
     main-net:
    logging:
      options: {max-file: '5', max-size: 100m}
    volumes:
      - "product-data:/var/lib/postgresql/data/"   

  product-data:
    image: rsp/product-data-service:dev
    user: "2000:2000"
    ports:
      - "8080:8080"
    networks:
      - main-net
    extra_hosts:
      - "edgex-core-data:172.17.0.1"
      - "edgex-support-logging:172.17.0.1"
      - "edgex-core-consul:172.17.0.1"
      - "edgex-core-command:172.17.0.1"
      - "edgex-support-notifications:172.17.0.1"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      options: {max-file: '5', max-size: 100m}
    environment:       
      port: "8080"         
      loggingLevel: "info"
      dbHost: "postgres-inventory"
      dbUser: "postgres"
      dbPass: ""
      dbPort: "5432"
      dbName: "postgres"
      dbSSLmode: "disable"
      zeroMQ: "edgex-core-data:5563"
      telemetryEndpoint: ""
      telemetryDataStoreName: "BadgerBay"
      responseLimit: 10000      
      serviceName: "Product Data Service"  