# Apache v2 license
#  Copyright (C) <2019> Intel Corporation
#
#  SPDX-License-Identifier: Apache-2.0
#

version: '3.4'

volumes:
  product-data: 

networks:
  main-net:

services:  

  postgres-inventory:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    networks:
     main-net:
    logging:
      options: {max-file: '5', max-size: 100m}
    volumes:
      - "product-data:/var/lib/postgresql/data/"   

  product-data:
    image: rsp/product-data-service:dev
    user: "2000:2000"
    ports:
      - "8080:8080"
    networks:
      - main-net
    extra_hosts:
      - "edgex-core-data:172.17.0.1"
      - "edgex-support-logging:172.17.0.1"
      - "edgex-core-consul:172.17.0.1"
      - "edgex-core-command:172.17.0.1"
      - "edgex-support-notifications:172.17.0.1"
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      options: {max-file: '5', max-size: 100m}
    environment:       
      port: "8080"         
      loggingLevel: "debug"
      dbHost: "postgres-inventory"
      dbUser: "postgres"
      dbPass: ""
      dbPort: "5432"
      dbName: "postgres"
      dbSSLmode: "disable"
      zeroMQ: "edgex-core-data:5563"
      telemetryEndpoint: ""
      telemetryDataStoreName: "inventory-suite"
      responseLimit: 10000      
      serviceName: "Product Data Service"  
